"use client";

import { useState } from 'react';
import {
  Download,
  FileText,
  FolderArchive,
  Layers,
  Globe2,
  Loader2,
  ChevronDown,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuLabel,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { useVaultStore } from '@/lib/store/vaultStore';
import { decryptSecret } from '@/lib/crypto/decrypt';
import { toast } from 'sonner';

interface ExportButtonProps {
  // Current context — all are optional; the component adapts based on what's provided
  projectId: string;
  projectName: string;
  environmentId?: string;
  environmentName?: string;
  folderId?: string | null;
  folderName?: string | null;
}

interface SecretPayload {
  id: string;
  keyName: string;
  valueEncrypted: string;
  iv: string;
}

interface FolderPayload {
  id: string;
  name: string;
  secrets: SecretPayload[];
}

interface EnvPayload {
  id: string;
  name: string;
  folders: FolderPayload[];
  rootSecrets: SecretPayload[];
}

interface ExportPayload {
  scope: string;
  projectName: string;
  environments: EnvPayload[];
}

async function decryptSecrets(
  secrets: SecretPayload[],
  environmentId: string,
  derivedKey: CryptoKey
): Promise<Record<string, string>> {
  const result: Record<string, string> = {};
  for (const secret of secrets) {
    try {
      const aad = `${secret.keyName}:${environmentId}`;
      result[secret.keyName] = await decryptSecret(secret.valueEncrypted, secret.iv, derivedKey, aad);
    } catch {
      result[`# ERROR_DECRYPTING_${secret.keyName}`] = '';
    }
  }
  return result;
}

function buildEnvFile(vars: Record<string, string>, header: string): string {
  let content = `# ${header}\n# Generated by EnVault — ${new Date().toLocaleString()}\n\n`;
  for (const [key, value] of Object.entries(vars)) {
    if (key.startsWith('#')) {
      content += `${key}\n`;
    } else {
      // Quote values that contain spaces or special chars
      const needsQuotes = /[\s"'\\#]/.test(value);
      content += needsQuotes ? `${key}="${value.replace(/"/g, '\\"')}"\n` : `${key}=${value}\n`;
    }
  }
  return content;
}

// Minimal zip builder (no external dependencies)
async function buildZip(files: { name: string; content: string }[]): Promise<Blob> {
  // Use CompressionStream with stored (no compression) entries in a zip-like structure
  // Falls back to a tar-like format since CompressionStream can't produce zip directly.
  // We'll use the File System Access API pattern with Blob construction.
  
  // Build a proper ZIP manually using the ZIP spec (stored, no compression)
  const encoder = new TextEncoder();
  const parts: Uint8Array[] = [];
  const centralDirectory: Uint8Array[] = [];
  let offset = 0;

  const crc32 = (data: Uint8Array): number => {
    const table = new Uint32Array(256);
    for (let i = 0; i < 256; i++) {
      let c = i;
      for (let j = 0; j < 8; j++) c = (c & 1) ? (0xedb88320 ^ (c >>> 1)) : (c >>> 1);
      table[i] = c;
    }
    let crc = 0xffffffff;
    for (const byte of data) crc = table[(crc ^ byte) & 0xff] ^ (crc >>> 8);
    return (crc ^ 0xffffffff) >>> 0;
  };

  const u16 = (n: number) => { const b = new Uint8Array(2); new DataView(b.buffer).setUint16(0, n, true); return b; };
  const u32 = (n: number) => { const b = new Uint8Array(4); new DataView(b.buffer).setUint32(0, n, true); return b; };

  for (const file of files) {
    const nameBytes = encoder.encode(file.name);
    const contentBytes = encoder.encode(file.content);
    const crc = crc32(contentBytes);
    const size = contentBytes.length;

    // Local file header
    const localHeader = new Uint8Array([
      0x50, 0x4b, 0x03, 0x04, // signature
      0x14, 0x00,             // version needed: 2.0
      0x00, 0x00,             // general purpose flags
      0x00, 0x00,             // compression: stored
      0x00, 0x00,             // mod time (ignored)
      0x00, 0x00,             // mod date (ignored)
      ...u32(crc),            // crc-32
      ...u32(size),           // compressed size
      ...u32(size),           // uncompressed size
      ...u16(nameBytes.length), // filename length
      0x00, 0x00,             // extra field length
      ...nameBytes,
      ...contentBytes,
    ]);
    parts.push(localHeader);

    // Central directory entry
    const cdEntry = new Uint8Array([
      0x50, 0x4b, 0x01, 0x02, // central dir signature
      0x14, 0x00,             // version made by
      0x14, 0x00,             // version needed
      0x00, 0x00,             // flags
      0x00, 0x00,             // compression: stored
      0x00, 0x00,             // mod time
      0x00, 0x00,             // mod date
      ...u32(crc),
      ...u32(size),
      ...u32(size),
      ...u16(nameBytes.length),
      0x00, 0x00,             // extra field length
      0x00, 0x00,             // comment length
      0x00, 0x00,             // disk number start
      0x00, 0x00,             // internal attr
      0x00, 0x00, 0x00, 0x00, // external attr
      ...u32(offset),         // relative offset of local header
      ...nameBytes,
    ]);
    centralDirectory.push(cdEntry);
    offset += localHeader.length;
  }

  const cdOffset = offset;
  const cdBytes = new Uint8Array(centralDirectory.reduce((acc, e) => acc + e.length, 0));
  let cdPos = 0;
  for (const entry of centralDirectory) { cdBytes.set(entry, cdPos); cdPos += entry.length; }

  const eocd = new Uint8Array([
    0x50, 0x4b, 0x05, 0x06, // end of central dir signature
    0x00, 0x00,             // disk number
    0x00, 0x00,             // disk with central dir
    ...u16(files.length),   // entries on disk
    ...u16(files.length),   // total entries
    ...u32(cdBytes.length), // central dir size
    ...u32(cdOffset),       // central dir offset
    0x00, 0x00,             // comment length
  ]);

  const totalSize = parts.reduce((a, p) => a + p.length, 0) + cdBytes.length + eocd.length;
  const zipBytes = new Uint8Array(totalSize);
  let pos = 0;
  for (const part of parts) { zipBytes.set(part, pos); pos += part.length; }
  zipBytes.set(cdBytes, pos); pos += cdBytes.length;
  zipBytes.set(eocd, pos);

  return new Blob([zipBytes], { type: 'application/zip' });
}

function triggerDownload(url: string, filename: string) {
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function ExportButton({
  projectId,
  projectName,
  environmentId,
  environmentName,
  folderId,
  folderName,
}: ExportButtonProps) {
  const [isExporting, setIsExporting] = useState<string | null>(null);
  const derivedKey = useVaultStore((s) => s.derivedKey);
  const touchActivity = useVaultStore((s) => s.touchActivity);

  const runExport = async (
    scope: 'folder' | 'environment' | 'project',
    format: 'env' | 'zip'
  ) => {
    if (!derivedKey) {
      toast.error('Vault is locked. Please unlock first.');
      return;
    }

    const key = `${scope}-${format}`;
    setIsExporting(key);
    touchActivity();

    try {
      // Build query
      const params = new URLSearchParams({ scope });
      if (scope === 'folder') {
        if (!environmentId || !folderId) { toast.error('No folder selected'); return; }
        params.set('environmentId', environmentId);
        params.set('folderId', folderId);
      } else if (scope === 'environment') {
        if (!environmentId) { toast.error('No environment selected'); return; }
        params.set('environmentId', environmentId);
      } else {
        params.set('projectId', projectId);
      }

      const res = await fetch(`/api/export?${params.toString()}`);
      if (!res.ok) {
        const err = await res.json();
        throw new Error(err.error || 'Export failed');
      }

      const data: ExportPayload = await res.json();
      const zipFiles: { name: string; content: string }[] = [];

      for (const env of data.environments) {
        // Root secrets (no folder)
        if (env.rootSecrets.length > 0) {
          const decrypted = await decryptSecrets(env.rootSecrets, env.id, derivedKey);
          const header = `${data.projectName} / ${env.name}`;
          const content = buildEnvFile(decrypted, header);

          if (format === 'env' && data.environments.length === 1 && env.folders.length === 0) {
            const blob = new Blob([content], { type: 'text/plain' });
            triggerDownload(URL.createObjectURL(blob), `${env.name}.env`);
            toast.success('Downloaded successfully');
            return;
          }
          zipFiles.push({ name: `${env.name}/.env`, content });
        }

        // Per-folder secrets
        for (const folder of env.folders) {
          if (folder.secrets.length === 0) continue;
          const decrypted = await decryptSecrets(folder.secrets, env.id, derivedKey);
          const header = `${data.projectName} / ${env.name} / ${folder.name}`;
          const content = buildEnvFile(decrypted, header);

          if (format === 'env' && data.environments.length === 1 && env.folders.length === 1 && env.rootSecrets.length === 0) {
            const blob = new Blob([content], { type: 'text/plain' });
            triggerDownload(URL.createObjectURL(blob), `${env.name}-${folder.name}.env`);
            toast.success('Downloaded successfully');
            return;
          }
          zipFiles.push({ name: `${env.name}/${folder.name}.env`, content });
        }
      }

      if (zipFiles.length === 0) {
        toast.error('No secrets found to export');
        return;
      }

      if (format === 'env') {
        // Merge all into one flat .env file
        const merged = zipFiles.map(f => `# === ${f.name} ===\n${f.content}`).join('\n');
        const blob = new Blob([merged], { type: 'text/plain' });
        const filename = scope === 'project' ? `${data.projectName}.env` : `${environmentName || 'export'}.env`;
        triggerDownload(URL.createObjectURL(blob), filename);
      } else {
        const zip = await buildZip(zipFiles);
        const filename = scope === 'project' ? `${data.projectName}.zip` : `${environmentName || 'export'}.zip`;
        triggerDownload(URL.createObjectURL(zip), filename);
      }

      toast.success(`Exported ${zipFiles.length} file(s) successfully`);
    } catch (err) {
      console.error(err);
      toast.error((err as Error).message || 'Export failed');
    } finally {
      setIsExporting(null);
    }
  };

  const isLoading = isExporting !== null;
  const hasFolder = Boolean(folderId);
  const hasEnvironment = Boolean(environmentId);

  return (
    <DropdownMenu>
      <DropdownMenuTrigger
        render={
          <Button
            variant="ghost"
            size="sm"
            className="h-9 gap-1.5 text-slate-500 hover:text-indigo-600 hover:bg-indigo-50 text-xs font-medium px-2.5"
            disabled={isLoading}
          >
            {isLoading ? (
              <Loader2 className="w-3.5 h-3.5 animate-spin" />
            ) : (
              <Download className="w-3.5 h-3.5" />
            )}
            Export
            <ChevronDown className="w-3 h-3 opacity-60" />
          </Button>
        }
      />
      <DropdownMenuContent align="end" className="w-64">

        {/* Folder scope */}
        {hasFolder && (
          <>
            <DropdownMenuLabel className="flex items-center gap-1.5 text-xs text-slate-400 font-medium pb-1">
              <Layers className="w-3 h-3" />
              This Folder — <span className="text-slate-600 font-semibold truncate">{folderName || 'Current'}</span>
            </DropdownMenuLabel>
            <DropdownMenuItem
              className="cursor-pointer pl-5"
              onClick={() => runExport('folder', 'env')}
            >
              <FileText className="w-4 h-4 mr-2 text-indigo-400" />
              Download as .env
            </DropdownMenuItem>
            <DropdownMenuItem
              className="cursor-pointer pl-5"
              onClick={() => runExport('folder', 'zip')}
            >
              <FolderArchive className="w-4 h-4 mr-2 text-indigo-400" />
              Download as .zip
            </DropdownMenuItem>
            <DropdownMenuSeparator />
          </>
        )}

        {/* Environment scope */}
        {hasEnvironment && (
          <>
            <DropdownMenuLabel className="flex items-center gap-1.5 text-xs text-slate-400 font-medium pb-1">
              <Layers className="w-3 h-3" />
              Environment — <span className="text-slate-600 font-semibold truncate">{environmentName || 'Current'}</span>
            </DropdownMenuLabel>
            <DropdownMenuItem
              className="cursor-pointer pl-5"
              onClick={() => runExport('environment', 'env')}
            >
              <FileText className="w-4 h-4 mr-2 text-green-500" />
              All Folders → merged .env
            </DropdownMenuItem>
            <DropdownMenuItem
              className="cursor-pointer pl-5"
              onClick={() => runExport('environment', 'zip')}
            >
              <FolderArchive className="w-4 h-4 mr-2 text-green-500" />
              All Folders → .zip
            </DropdownMenuItem>
            <DropdownMenuSeparator />
          </>
        )}

        {/* Project scope (always visible) */}
        <DropdownMenuLabel className="flex items-center gap-1.5 text-xs text-slate-400 font-medium pb-1">
          <Globe2 className="w-3 h-3" />
          Project — <span className="text-slate-600 font-semibold truncate">{projectName}</span>
        </DropdownMenuLabel>
        <DropdownMenuItem
          className="cursor-pointer pl-5"
          onClick={() => runExport('project', 'env')}
        >
          <FileText className="w-4 h-4 mr-2 text-violet-500" />
          All Environments → merged .env
        </DropdownMenuItem>
        <DropdownMenuItem
          className="cursor-pointer pl-5"
          onClick={() => runExport('project', 'zip')}
        >
          <FolderArchive className="w-4 h-4 mr-2 text-violet-500" />
          All Environments → .zip
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
